#ifndef __RF24G_KEY_H 
#define __RF24G_KEY_H 

#include "includes.h"



// 定义按键键值：
enum
{
    RF24G_KEY_ON_OFF = 0x01, // 开关机

    RF24G_KEY_CHROMATIC_CIRCLE, // 色环

    RF24G_KEY_MODE_ADD = 0x05,
    RF24G_KEY_MODE_SUB = 0X0B,

    RF24G_KEY_SPEED_SUB = 0x07,
    RF24G_KEY_SPEED_ADD = 0x09,

    RF24G_KEY_DEMO = 0x08,

    RF24G_KEY_COLOR_ADD = 0x0A,
    RF24G_KEY_COLOR_SUB = 0x0D,

    RF24G_KEY_BRIGHT_ADD = 0x0C,
    RF24G_KEY_BRIGHT_SUB = 0x0F,

    RF24G_KEY_A = 0x0E,
    RF24G_KEY_B = 0x10,
    RF24G_KEY_C = 0x11,
    RF24G_KEY_D = 0x12,
    RF24G_KEY_E = 0x13,
    RF24G_KEY_F = 0x14,
    RF24G_KEY_G = 0x15,

    // RF24G_KEY_NONE, // 无按键
};

// 定义按键事件
enum
{
    RF24G_KEY_EVENT_NONE = 0x00,

    RF24G_KEY_EVENT_ON_OFF_CLICK,
    RF24G_KEY_EVENT_ON_OFF_HOLD,
    RF24G_KEY_EVENT_ON_OFF_LOOSE,

    RF24G_KEY_EVENT_MODE_ADD_CLICK,
    RF24G_KEY_EVENT_MODE_ADD_HOLD,
    RF24G_KEY_EVENT_MODE_ADD_LOOSE,

    RF24G_KEY_EVENT_MODE_SUB_CLICK,
    RF24G_KEY_EVENT_MODE_SUB_HOLD,
    RF24G_KEY_EVENT_MODE_SUB_LOOSE,

    RF24G_KEY_EVENT_SPEED_ADD_CLICK,
    RF24G_KEY_EVENT_SPEED_ADD_HOLD,
    RF24G_KEY_EVENT_SPEED_ADD_LOOSE,

    RF24G_KEY_EVENT_SPEED_SUB_CLICK,
    RF24G_KEY_EVENT_SPEED_SUB_HOLD,
    RF24G_KEY_EVENT_SPEED_SUB_LOOSE,

    RF24G_KEY_EVENT_DEMO_CLICK,
    RF24G_KEY_EVENT_DEMO_HOLD,
    RF24G_KEY_EVENT_DEMO_LOOSE,

    RF24G_KEY_EVENT_COLOR_ADD_CLICK,
    RF24G_KEY_EVENT_COLOR_ADD_HOLD,
    RF24G_KEY_EVENT_COLOR_ADD_LOOSE,

    RF24G_KEY_EVENT_COLOR_SUB_CLICK,
    RF24G_KEY_EVENT_COLOR_SUB_HOLD,
    RF24G_KEY_EVENT_COLOR_SUB_LOOSE,

    RF24G_KEY_EVENT_BRIGHT_ADD_CLICK,
    RF24G_KEY_EVENT_BRIGHT_ADD_HOLD,
    RF24G_KEY_EVENT_BRIGHT_ADD_LOOSE,

    RF24G_KEY_EVENT_BRIGHT_SUB_CLICK,
    RF24G_KEY_EVENT_BRIGHT_SUB_HOLD,
    RF24G_KEY_EVENT_BRIGHT_SUB_LOOSE,

    // 字母B
    RF24G_KEY_EVENT_B_CLICK,
    RF24G_KEY_EVENT_B_HOLD,
    RF24G_KEY_EVENT_B_LOOSE,

    // 字母F
    RF24G_KEY_EVENT_F_CLICK,
    RF24G_KEY_EVENT_F_HOLD,
    RF24G_KEY_EVENT_F_LOOSE,
    // 字母G
    RF24G_KEY_EVENT_G_CLICK,
    RF24G_KEY_EVENT_G_HOLD,
    RF24G_KEY_EVENT_G_LOOSE,
};
#define RF34G_KEY_EVENT_MAX (3) // 按键事件种类个数， 短按、持续hold、松开

#define RF24G_KEY_SCAN_TIME_MS (10) // 2.4G遥控器按键扫描频率，单位：ms
#define RF24G_KEY_LONG_TIME_MS (1500)
#define RF24G_KEY_HOLD_TIME_MS (500)
#define RF24G_KEY_SCAN_CLICK_DELAY_TIME_MS (0) // 2.4G遥控器按键被抬起后等待连击延时数量
#define RF24G_KEY_SCAN_FILTER_TIME_MS (0)      // 2.4G遥控器按键消抖延时

#define HEADER1_1 0x55
#define HEADER2_1 0xAA



#endif // end of file